"""
models.py
---------
SQLAlchemy ORM models for Lodestone.

Each class here represents one database table. SQLAlchemy maps:
  - class  → table
  - attribute → column
  - instance → row

These classes are registered with the shared Base from db.py.
When db.create_tables() is called, SQLAlchemy translates these
class definitions into SQL CREATE TABLE statements.
"""

from datetime import datetime
from sqlalchemy import Column, String, Text, Integer, DateTime
from db import Base


class Session(Base):
    """
    Stores one active learning session per student-problem pair.

    The most important column is state_json: the entire LodestoneState dict
    (from graph/state.py) is serialized to JSON and stored here between
    API calls. When the next request arrives, we deserialize it back into
    a Python dict and hand it to LangGraph to continue processing.

    This is the "manual checkpointing" approach described in the spec —
    simpler than LangGraph's built-in checkpointer for our use case.
    """
    __tablename__ = "sessions"

    # Primary key: a UUID string generated by the route handler on session creation.
    id = Column(String, primary_key=True)

    # Who is working on this session.
    student_id = Column(String, nullable=False)

    # Which problem assignment this session is for.
    problem_id = Column(String, nullable=False)

    # The full LodestoneState dict serialized to a JSON string.
    # We use Text (unlimited length) because state can grow large
    # (spec_history and chat_history accumulate many turns).
    state_json = Column(Text, nullable=False)

    # The current graph phase — redundant with state_json["phase"] but
    # stored here for fast querying (e.g. "show me all students in spec_gate")
    # without deserializing every state_json blob.
    phase = Column(String, nullable=False, default="spec_gate")

    # Timestamps — default= runs once at INSERT time; onupdate= runs at UPDATE time.
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class StudentSKS(Base):
    """
    Persists the Student Knowledge State (SKS) across sessions.

    Unlike Session (one row per session), this is one row per student —
    it accumulates across all their sessions using an exponential moving
    average (see update_sks node in graph/nodes.py).

    The sks_json column holds the full SKS dict:
    {
        "topic_scores": {"recursion": 0.4, "arrays": 0.8},
        "mistake_patterns": ["forgets null checks"],
        "avg_hint_level_needed": 2.3
    }
    """
    __tablename__ = "student_sks"

    # One row per student. Using student_id as primary key means
    # upsert logic is: "if row exists, UPDATE it; else INSERT."
    student_id = Column(String, primary_key=True)

    # Full SKS dict serialized as JSON.
    sks_json = Column(Text, nullable=False)

    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class CohortEvent(Base):
    """
    An append-only event log for notable things that happen during sessions.

    Events are written by update_sks and intent_diff nodes. The dashboard
    reads this table with a simple GROUP BY event_type query to show teachers
    patterns across their entire class (cohort).

    Examples of event_type values:
      "spec_miss"       → student's spec had a gap caught by spec_gate
      "compiler_error"  → student's code failed to compile
      "intent_mismatch" → student's code didn't match their spec on submit

    This table is intentionally append-only — we never UPDATE or DELETE rows.
    This preserves the full history for future analytics.
    """
    __tablename__ = "cohort_events"

    # Auto-incrementing integer primary key — we don't need UUID here
    # since events are never referenced by ID from outside.
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Groups students into a class/cohort for the dashboard.
    cohort_id = Column(String, nullable=False)

    student_id = Column(String, nullable=False)

    # References the session where this event occurred.
    session_id = Column(String, nullable=False)

    # The category of event (see examples in class docstring).
    event_type = Column(String, nullable=False)

    # A human-readable explanation or the raw LLM output for this event.
    detail = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
